apiVersion: v1
data:
  kube.conf: |-
    # Fluentd config file for OMS Docker - cluster components (kubeAPI)
    #fluent forward plugin
    <source>
     type forward
     port "#{ENV['HEALTHMODEL_REPLICASET_SERVICE_SERVICE_PORT']}"
     bind 0.0.0.0
     chunk_size_limit 4m
    </source>

    #Kubernetes pod inventory
    <source>
     type kubepodinventory
     tag oms.containerinsights.KubePodInventory
     run_interval 60
     log_level debug
    </source>

    #Kubernetes Persistent Volume inventory
    <source>
     type kubepvinventory
     tag oms.containerinsights.KubePVInventory
     run_interval 60
     log_level debug
    </source>

    #Kubernetes events
    <source>
     type kubeevents
     tag oms.containerinsights.KubeEvents
     run_interval 60
     log_level debug
    </source>

    #Kubernetes Nodes
    <source>
     type kubenodeinventory
     tag oms.containerinsights.KubeNodeInventory
     run_interval 60
     log_level debug
    </source>

    #Kubernetes health
    <source>
     type kubehealth
     tag kubehealth.ReplicaSet
     run_interval 60
     log_level debug
    </source>

    #cadvisor perf- Windows nodes
    <source>
     type wincadvisorperf
     tag oms.api.wincadvisorperf
     run_interval 60
     log_level debug
    </source>

    #Kubernetes object state - deployments
    <source>
     type kubestatedeployments
     tag oms.containerinsights.KubeStateDeployments
     run_interval 60
     log_level debug
    </source>

    #Kubernetes object state - HPA
    <source>
     type kubestatehpa
     tag oms.containerinsights.KubeStateHpa
     run_interval 60
     log_level debug
    </source>

    <filter mdm.kubenodeinventory**>
     type filter_inventory2mdm
     log_level info
    </filter>

    #custom_metrics_mdm filter plugin for perf data from windows nodes
    <filter mdm.cadvisorperf**>
     type filter_cadvisor2mdm
     metrics_to_collect cpuUsageNanoCores,memoryWorkingSetBytes,pvUsedBytes
     log_level info
    </filter>

    #health model aggregation filter
    <filter kubehealth**>
     type filter_health_model_builder
    </filter>

    <match oms.containerinsights.KubePodInventory**>
     type out_oms
     log_level debug
     num_threads 2
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/out_oms_kubepods*.buffer
     buffer_queue_limit 20
     buffer_queue_full_action drop_oldest_chunk
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
    </match>

    <match oms.containerinsights.KubePVInventory**>
     type out_oms
     log_level debug
     num_threads 5
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/state/out_oms_kubepv*.buffer
     buffer_queue_limit 20
     buffer_queue_full_action drop_oldest_chunk
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
    </match>

    <match oms.containerinsights.KubeEvents**>
     type out_oms
     log_level debug
     num_threads 2
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/out_oms_kubeevents*.buffer
     buffer_queue_limit 20
     buffer_queue_full_action drop_oldest_chunk
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
    </match>

    <match oms.containerinsights.KubeServices**>
     type out_oms
     log_level debug
     num_threads 2
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/out_oms_kubeservices*.buffer
     buffer_queue_limit 20
     buffer_queue_full_action drop_oldest_chunk
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
    </match>

    <match oms.containerinsights.KubeNodeInventory**>
     type out_oms
     log_level debug
     num_threads 2
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/state/out_oms_kubenodes*.buffer
     buffer_queue_limit 20
     buffer_queue_full_action drop_oldest_chunk
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
    </match>

    <match oms.containerinsights.ContainerNodeInventory**>
     type out_oms
     log_level debug
     num_threads 3
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/out_oms_containernodeinventory*.buffer
     buffer_queue_limit 20
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
    </match>

    <match oms.api.KubePerf**>
     type out_oms
     log_level debug
     num_threads 2
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/out_oms_kubeperf*.buffer
     buffer_queue_limit 20
     buffer_queue_full_action drop_oldest_chunk
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
    </match>

    <match mdm.kubepodinventory** mdm.kubenodeinventory** >
     type out_mdm
     log_level debug
     num_threads 5
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/out_mdm_*.buffer
     buffer_queue_limit 20
     buffer_queue_full_action drop_oldest_chunk
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
     retry_mdm_post_wait_minutes 30
    </match>

    <match oms.api.wincadvisorperf**>
     type out_oms
     log_level debug
     num_threads 5
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/out_oms_api_wincadvisorperf*.buffer
     buffer_queue_limit 20
     buffer_queue_full_action drop_oldest_chunk
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
    </match>

    <match mdm.cadvisorperf**>
     type out_mdm
     log_level debug
     num_threads 5
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/out_mdm_cdvisorperf*.buffer
     buffer_queue_limit 20
     buffer_queue_full_action drop_oldest_chunk
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
     retry_mdm_post_wait_minutes 30
    </match>

    <match kubehealth.Signals**>
     type out_oms
     log_level debug
     num_threads 5
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/out_oms_kubehealth*.buffer
     buffer_queue_limit 20
     buffer_queue_full_action drop_oldest_chunk
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
    </match>
    <match oms.api.InsightsMetrics**>
     type out_oms
     log_level debug
     num_threads 5
     buffer_chunk_limit 4m
     buffer_type file
     buffer_path %STATE_DIR_WS%/out_oms_insightsmetrics*.buffer
     buffer_queue_limit 20
     buffer_queue_full_action drop_oldest_chunk
     flush_interval 20s
     retry_limit 10
     retry_wait 5s
     max_retry_wait 5m
    </match>
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"kube.conf":"# Fluentd config file for OMS Docker - cluster components (kubeAPI)\n#fluent forward plugin\n\u003csource\u003e\n type forward\n port \"#{ENV['HEALTHMODEL_REPLICASET_SERVICE_SERVICE_PORT']}\"\n bind 0.0.0.0\n chunk_size_limit 4m\n\u003c/source\u003e\n\n#Kubernetes pod inventory\n\u003csource\u003e\n type kubepodinventory\n tag oms.containerinsights.KubePodInventory\n run_interval 60\n log_level debug\n\u003c/source\u003e\n\n#Kubernetes Persistent Volume inventory\n\u003csource\u003e\n type kubepvinventory\n tag oms.containerinsights.KubePVInventory\n run_interval 60\n log_level debug\n\u003c/source\u003e\n\n#Kubernetes events\n\u003csource\u003e\n type kubeevents\n tag oms.containerinsights.KubeEvents\n run_interval 60\n log_level debug\n\u003c/source\u003e\n\n#Kubernetes Nodes\n\u003csource\u003e\n type kubenodeinventory\n tag oms.containerinsights.KubeNodeInventory\n run_interval 60\n log_level debug\n\u003c/source\u003e\n\n#Kubernetes health\n\u003csource\u003e\n type kubehealth\n tag kubehealth.ReplicaSet\n run_interval 60\n log_level debug\n\u003c/source\u003e\n\n#cadvisor perf- Windows nodes\n\u003csource\u003e\n type wincadvisorperf\n tag oms.api.wincadvisorperf\n run_interval 60\n log_level debug\n\u003c/source\u003e\n\n#Kubernetes object state - deployments\n\u003csource\u003e\n type kubestatedeployments\n tag oms.containerinsights.KubeStateDeployments\n run_interval 60\n log_level debug\n\u003c/source\u003e\n\n#Kubernetes object state - HPA\n\u003csource\u003e\n type kubestatehpa\n tag oms.containerinsights.KubeStateHpa\n run_interval 60\n log_level debug\n\u003c/source\u003e\n\n\u003cfilter mdm.kubenodeinventory**\u003e\n type filter_inventory2mdm\n log_level info\n\u003c/filter\u003e\n\n#custom_metrics_mdm filter plugin for perf data from windows nodes\n\u003cfilter mdm.cadvisorperf**\u003e\n type filter_cadvisor2mdm\n metrics_to_collect cpuUsageNanoCores,memoryWorkingSetBytes,pvUsedBytes\n log_level info\n\u003c/filter\u003e\n\n#health model aggregation filter\n\u003cfilter kubehealth**\u003e\n type filter_health_model_builder\n\u003c/filter\u003e\n\n\u003cmatch oms.containerinsights.KubePodInventory**\u003e\n type out_oms\n log_level debug\n num_threads 2\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/out_oms_kubepods*.buffer\n buffer_queue_limit 20\n buffer_queue_full_action drop_oldest_chunk\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n\u003c/match\u003e\n\n\u003cmatch oms.containerinsights.KubePVInventory**\u003e\n type out_oms\n log_level debug\n num_threads 5\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/state/out_oms_kubepv*.buffer\n buffer_queue_limit 20\n buffer_queue_full_action drop_oldest_chunk\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n\u003c/match\u003e\n\n\u003cmatch oms.containerinsights.KubeEvents**\u003e\n type out_oms\n log_level debug\n num_threads 2\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/out_oms_kubeevents*.buffer\n buffer_queue_limit 20\n buffer_queue_full_action drop_oldest_chunk\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n\u003c/match\u003e\n\n\u003cmatch oms.containerinsights.KubeServices**\u003e\n type out_oms\n log_level debug\n num_threads 2\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/out_oms_kubeservices*.buffer\n buffer_queue_limit 20\n buffer_queue_full_action drop_oldest_chunk\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n\u003c/match\u003e\n\n\u003cmatch oms.containerinsights.KubeNodeInventory**\u003e\n type out_oms\n log_level debug\n num_threads 2\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/state/out_oms_kubenodes*.buffer\n buffer_queue_limit 20\n buffer_queue_full_action drop_oldest_chunk\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n\u003c/match\u003e\n\n\u003cmatch oms.containerinsights.ContainerNodeInventory**\u003e\n type out_oms\n log_level debug\n num_threads 3\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/out_oms_containernodeinventory*.buffer\n buffer_queue_limit 20\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n\u003c/match\u003e\n\n\u003cmatch oms.api.KubePerf**\u003e\n type out_oms\n log_level debug\n num_threads 2\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/out_oms_kubeperf*.buffer\n buffer_queue_limit 20\n buffer_queue_full_action drop_oldest_chunk\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n\u003c/match\u003e\n\n\u003cmatch mdm.kubepodinventory** mdm.kubenodeinventory** \u003e\n type out_mdm\n log_level debug\n num_threads 5\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/out_mdm_*.buffer\n buffer_queue_limit 20\n buffer_queue_full_action drop_oldest_chunk\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n retry_mdm_post_wait_minutes 30\n\u003c/match\u003e\n\n\u003cmatch oms.api.wincadvisorperf**\u003e\n type out_oms\n log_level debug\n num_threads 5\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/out_oms_api_wincadvisorperf*.buffer\n buffer_queue_limit 20\n buffer_queue_full_action drop_oldest_chunk\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n\u003c/match\u003e\n\n\u003cmatch mdm.cadvisorperf**\u003e\n type out_mdm\n log_level debug\n num_threads 5\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/out_mdm_cdvisorperf*.buffer\n buffer_queue_limit 20\n buffer_queue_full_action drop_oldest_chunk\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n retry_mdm_post_wait_minutes 30\n\u003c/match\u003e\n\n\u003cmatch kubehealth.Signals**\u003e\n type out_oms\n log_level debug\n num_threads 5\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/out_oms_kubehealth*.buffer\n buffer_queue_limit 20\n buffer_queue_full_action drop_oldest_chunk\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n\u003c/match\u003e\n\u003cmatch oms.api.InsightsMetrics**\u003e\n type out_oms\n log_level debug\n num_threads 5\n buffer_chunk_limit 4m\n buffer_type file\n buffer_path %STATE_DIR_WS%/out_oms_insightsmetrics*.buffer\n buffer_queue_limit 20\n buffer_queue_full_action drop_oldest_chunk\n flush_interval 20s\n retry_limit 10\n retry_wait 5s\n max_retry_wait 5m\n\u003c/match\u003e"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"ama-logs-rs-config","namespace":"kube-system"}}
  creationTimestamp: "2022-12-10T17:50:12Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  name: ama-logs-rs-config
  namespace: kube-system
  resourceVersion: "17553579"
  uid: 942ff5cc-5df2-44cc-a65a-0feaff16d405
